apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - "**"

jobs:
  build:
    environment: qa-test
    steps:
      - name: listfiles
        uses: docker://golang:1.20
        kind: build
        run: |
          ls -lrta

      - name: listfiles
        uses: docker://golang:1.20
        kind: deploy
        run: |
          ls -lrta

      - name: Sonarqube
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        kind: scan
        with:
          language: LANGUAGE_GO
